"""empty message

Revision ID: 82a311a635f6
Revises: d76edef4de95
Create Date: 2023-11-03 20:21:08.635742

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "82a311a635f6"
down_revision: Union[str, None] = "d76edef4de95"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("level", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "level")
    # ### end Alembic commands ###
