"""empty message

Revision ID: 896d1546f1d8
Revises: 0f05679076a3
Create Date: 2023-11-02 20:55:19.975224

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '896d1546f1d8'
down_revision: Union[str, None] = '0f05679076a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('snils', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'snils')
    # ### end Alembic commands ###
