"""empty message

Revision ID: d6fe2acdacea
Revises: 95e0167fdacd
Create Date: 2023-11-02 21:01:36.072216

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d6fe2acdacea"
down_revision: Union[str, None] = "95e0167fdacd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "core.person",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("fio", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_core.person_id"), "core.person", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_core.person_id"), table_name="core.person")
    op.drop_table("core.person")
    # ### end Alembic commands ###
