"""empty message

Revision ID: faa43212970f
Revises: d6fe2acdacea
Create Date: 2023-11-02 21:03:02.533677

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'faa43212970f'
down_revision: Union[str, None] = 'd6fe2acdacea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('core.person', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'core.person', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'core.person', type_='foreignkey')
    op.drop_column('core.person', 'user_id')
    # ### end Alembic commands ###
